package org.silentsoft.slack.api;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;
import org.silentsoft.net.rest.RESTfulAPI;

/**
 * <code>token</code> can be generated by two ways.</br>
 * <pre><li><a href="https://api.slack.com/custom-integrations/legacy-tokens">legacy-tokens</a>
 * 1. Visit Legacy Tokens page at https://api.slack.com/custom-integrations/legacy-tokens.
 * 2. Click Create token.
 * </li></pre>
 * <pre><li><a href="https://api.slack.com/apps">apps</a>
 * 1. Create an App from https://api.slack.com/apps.
 * 2. Features > OAuth & Permissions > Scopes > Bot Token Scopes > "channels:read", "chat:write".
 * 3. Features > OAuth & Permissions > OAuth Tokens & Redirect URLs > Install App to Workspace.
 * 4. Add an App to specific channel.
 * </li></pre>
 * 
 * @author silentsoft
 *
 */
public class SlackAPI {
	
	/**
	 * 
	 * @param token Legacy token or OAuth Access Token.
	 * @param channel Name or encoded ID.
	 * @param text Message to post.
	 * @return
	 * @throws Exception
	 * @see https://api.slack.com/methods/chat.postMessage
	 */
	@SuppressWarnings("unchecked")
	public static Map<String, Object> postMessage(String token, String channel, String text) throws Exception {
		List<NameValuePair> params = new ArrayList<NameValuePair>();
		params.add(new BasicNameValuePair("token", token));
		params.add(new BasicNameValuePair("channel", channel));
		params.add(new BasicNameValuePair("text", text));
		
		return RESTfulAPI.doPost("https://slack.com/api/chat.postMessage", params, Map.class);
	}

}
