package org.silentsoft.slack.api;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

import org.apache.http.NameValuePair;
import org.apache.http.message.BasicNameValuePair;
import org.silentsoft.net.rest.RESTfulAPI;

/**
 * <code>token</code> can be generated by two ways.<p></p>
 * 
 * <a href="https://api.slack.com/custom-integrations/legacy-tokens">legacy-tokens</a>
 * <ol>
 * <li>Visit Legacy Tokens page at https://api.slack.com/custom-integrations/legacy-tokens.</li>
 * <li>Click Create token.</li>
 * </ol>
 * 
 * <a href="https://api.slack.com/apps">apps</a>
 * <ol>
 * <li>Create an App from https://api.slack.com/apps.</li>
 * <li>Features &gt; OAuth &amp; Permissions &gt; Scopes &gt; Bot Token Scopes &gt; "channels:read", "chat:write".</li>
 * <li>Features &gt; OAuth &amp; Permissions &gt; OAuth Tokens &amp; Redirect URLs &gt; Install App to Workspace.</li>
 * <li>Add an App to specific channel.</li>
 * </ol>
 * 
 * @author silentsoft
 */
public class SlackAPI {
	
	/**
	 * 
	 * @param token Legacy token or OAuth Access Token.
	 * @param channel Name or encoded ID.
	 * @param text Message to post.
	 * @return
	 * @throws Exception
	 * @see <a href="https://api.slack.com/methods/chat.postMessage">https://api.slack.com/methods/chat.postMessage</a>
	 */
	@SuppressWarnings("unchecked")
	public static Map<String, Object> postMessage(String token, String channel, String text) throws Exception {
		List<NameValuePair> params = new ArrayList<NameValuePair>();
		params.add(new BasicNameValuePair("token", token));
		params.add(new BasicNameValuePair("channel", channel));
		params.add(new BasicNameValuePair("text", text));
		
		return RESTfulAPI.doPost("https://slack.com/api/chat.postMessage", params, Map.class);
	}

}
